name: Deploy site files

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use Node.js 14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "14.x"

      - name: Build
        run: |
          yarn install
          yarn run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
        with:
          forceOrphan: true
          BRANCH: gh-pages
